### Инициализация проекта

In [91]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings

In [92]:
data = pd.read_csv('data/smoke_detector_task.csv')

### Исследование исходных данных

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62630 entries, 0 to 62629
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      62630 non-null  int64
 1   UTC             62630 non-null  int64
 2   Temperature[C]  62484 non-null  float64
 3   Humidity[%]     62383 non-null  float64
 4   TVOC[ppb]       62009 non-null  float64
 5   eCO2[ppm]       62305 non-null  float64
 6   Raw H2          62519 non-null  float64
 7   Raw Ethanol     62630 non-null  int64
 8   Pressure[hPa]   62603 non-null  float64
 9   PM1.0           62630 non-null  float64
 10  PM2.5           62313 non-null  float64
 11  NC0.5           62630 non-null  float64
 12  NC1.0           62378 non-null  float64
 13  NC2.5           62630 non-null  float64
 14  CNT             62630 non-null  int64
 15  Fire Alarm      62630 non-null  object
dtypes: float64(11), int64(4), object(1)
memory usage: 7.6+ MB

2 лишних поля: "Unnamed: 0" и "CNT" - не несут никакой смысловой нагрузки, "CNT" - просто счётчик от 1 и до длины датасета

In [94]:
data = data.drop("Unnamed: 0", axis=1)
data = data.drop("CNT", axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62630 entries, 0 to 62629
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UTC             62630 non-null  int64
 1   Temperature[C]  62484 non-null  float64
 2   Humidity[%]     62383 non-null  float64
 3   TVOC[ppb]       62009 non-null  float64
 4   eCO2[ppm]       62305 non-null  float64
 5   Raw H2          62519 non-null  float64
 6   Raw Ethanol     62630 non-null  int64
 7   Pressure[hPa]   62603 non-null  float64
 8   PM1.0           62630 non-null  float64
 9   PM2.5           62313 non-null  float64
 10  NC0.5           62630 non-null  float64
 11  NC1.0           62378 non-null  float64
 12  NC2.5           62630 non-null  float64
 13  Fire Alarm      62630 non-null  object
dtypes: float64(11), int64(2), object(1)
memory usage: 6.7+ MB

In [95]:
data.describe()

,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5
count,6.263000e+04,62484.000000,62383.000000,62009.000000,62305.000000,62519.000000,62630.000000,62603.000000,62630.000000,62313.000000,62630.000000,62378.000000,62630.000000
mean,1.654792e+09,15.972252,48.536969,1944.124030,670.574994,12942.383835,19754.257912,938.627644,100.594309,184.443467,491.463608,203.382660,80.049042
std,1.100025e+05,14.361206,8.868993,7819.668069,1909.675941,272.531480,609.513156,1.331169,922.524245,1976.590473,4265.661251,2214.719662,1083.383189
min,1.654712e+09,-22.010000,10.740000,0.000000,400.000000,10668.000000,15317.000000,930.852000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.654743e+09,11.000500,47.530000,130.000000,400.000000,12830.000000,19435.000000,938.700000,1.280000,1.340000,8.820000,1.384000,0.033000
50%,1.654762e+09,20.130000,50.140000,981.000000,400.000000,12924.000000,19501.000000,938.816000,1.810000,1.880000,12.450000,1.942000,0.044000
75%,1.654778e+09,25.410000,53.240000,1189.000000,438.000000,13108.000000,20078.000000,939.417000,2.090000,2.180000,14.420000,2.249000,0.051000
max,1.655130e+09,59.930000,75.200000,60000.000000,60000.000000,13803.000000,21410.000000,939.861000,14333.690000,45432.260000,61482.030000,51914.680000,30026.438000

In [96]:
data.head(20)

,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,Fire Alarm
0,1654733331,20.000,57.36,0.0,400.0,12306.0,18520,939.735,0.00,0.00,0.0,0.000,0.000,No
1,1654733332,20.015,56.67,0.0,400.0,12345.0,18651,939.744,0.00,0.00,0.0,0.000,0.000,No
2,1654733333,20.029,55.96,0.0,400.0,12374.0,18764,939.738,0.00,0.00,0.0,0.000,0.000,No
3,1654733334,20.044,55.28,0.0,400.0,12390.0,18849,939.736,0.00,0.00,0.0,0.000,0.000,No
4,1654733335,20.059,54.69,0.0,400.0,12403.0,18921,939.744,0.00,0.00,0.0,0.000,0.000,No
5,1654733336,20.073,54.12,0.0,400.0,12419.0,18998,939.725,0.00,0.00,0.0,0.000,0.000,No
6,1654733337,20.088,53.61,0.0,400.0,12432.0,19058,939.738,0.00,0.00,0.0,0.000,0.000,No
7,1654733338,20.103,53.20,0.0,400.0,12439.0,19114,939.758,0.00,0.00,0.0,0.000,0.000,No
8,1654733339,20.117,52.81,0.0,400.0,12448.0,19155,939.758,0.00,0.00,0.0,0.000,0.000,No
9,1654733340,20.132,52.46,0.0,400.0,12453.0,19195,939.756,0.90,3.78,0.0,4.369,2.780,No
10,1654733341,20.146,52.15,0.0,400.0,12454.0,19230,939.757,0.89,3.71,0.0,4.289,2.730,No
11,1654733342,20.161,51.84,0.0,400.0,12467.0,19264,939.754,0.84,3.51,0.0,4.053,2.580,No
12,1654733343,20.175,51.62,0.0,400.0,12467.0,19299,939.755,0.81,3.38,0.0,3.909,2.488,No
13,1654733344,20.190,51.39,0.0,400.0,12469.0,19317,939.758,0.74,3.11,0.0,3.588,2.284,No
14,1654733345,20.204,51.17,0.0,403.0,12468.0,19338,939.742,0.71,2.96,0.0,3.419,2.176,No
15,1654733346,20.219,50.99,0.0,400.0,12475.0,19362,939.741,0.64,2.66,0.0,3.077,1.959,No
16,1654733347,20.233,50.86,0.0,400.0,12480.0,19382,939.758,0.60,2.52,0.0,2.908,1.851,No
17,1654733348,20.248,50.66,0.0,400.0,12477.0,19400,939.764,0.53,2.23,0.0,2.580,1.642,No
18,1654733349,20.262,50.49,0.0,400.0,12481.0,19422,939.761,0.50,2.10,0.0,2.423,1.542,No
19,1654733350,20.277,50.27,0.0,406.0,12489.0,19451,939.752,0.41,1.72,0.0,1.987,1.265,No

<font size=4>
Датасет содержит следующие поля:

- `UTC` — время
- `Temperature[C]` — температура
- `Humidity[%]` — влажность
- `TVOC[ppb]` — содержание летучих органических соединений в воздухе и показания в виде концентрации TVOC - в частях на миллиард (ppb)
- `eCO2[ppm]` — концентрация молекул углекислого газа (CO2) в воздухе
- `Raw H2` — концентрации водорода (H₂)
- `Raw Ethanol` — сырое (необработанное) значение концентрации этанола (C₂H₅OH)
- `Pressure[hPa]` — давление воздуха, измеряемое в гектопаскалях (hPa)
- `PM1.0` — твёрдые частицы в воздухе ≤ 1.0 мкм (ультрамелкие частицы)
- `PM2.5` — частицы ≤ 2.5 мкм (мелкие частицы, опасные для здоровья)
- `NC0.5` — количество частиц определённого размера, концентрация частиц ≤ 0.5 мкм
- `NC1.0` — концентрация частиц ≤ 1.0 мкм
- `NC2.5` — концентрация частиц ≤ 2.5 мкм
- `Fire Alarm` — сработал ли датчик
</font>

Заключение по исходным данным:
- поле "Fire Alarm" следует перевести из типа object в тип bool
- поля "TVOC[ppb]", "eCO2[ppm]", "Raw H2" следует перевести из типа float в тип int
- "UTC" перевести в datetime

### Заполнение пропусков

In [97]:
(data.isna().sum() / data.shape[0] * 100).sort_values(ascending=False)

TVOC[ppb]         0.991538
eCO2[ppm]         0.518921
PM2.5             0.506147
NC1.0             0.402363
Humidity[%]       0.394380
Temperature[C]    0.233115
Raw H2            0.177231
Pressure[hPa]     0.043110
UTC               0.000000
Raw Ethanol       0.000000
PM1.0             0.000000
NC0.5             0.000000
NC2.5             0.000000
Fire Alarm        0.000000
dtype: float64